from fastapi import FastAPI, Depends, HTTPException, UploadFile, File, Form
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from sqlalchemy import func, inspect
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session
from pydantic import BaseModel
from typing import List
from datetime import datetime
from io import BytesIO
from fastapi.responses import StreamingResponse
from pathlib import Path
import uuid

import models
from database import engine, get_db

# Create the database tables
models.Base.metadata.create_all(bind=engine)

# Initialize FastAPI App
app = FastAPI(title="BITS Fee Portal API")

ALERT_STORE = {}
REJECTION_REASON_STORE = {}
UPLOADS_DIR = Path("uploads")
UPLOADS_DIR.mkdir(parents=True, exist_ok=True)


def push_alert_for_student(student_id: int, title: str, message: str, notification_type: str = "ALERT"):
    notifications = ALERT_STORE.get(student_id, [])
    notifications.insert(0, {
        "id": f"NTF-{int(datetime.utcnow().timestamp() * 1000)}-{student_id}",
        "type": notification_type,
        "title": title,
        "message": message,
        "time": "Just now",
        "read": False
    })
    ALERT_STORE[student_id] = notifications[:20]


def get_fee_category_title(db: Session, fee_category_id: int) -> str:
    category = db.query(models.FeeCategory).filter(models.FeeCategory.id == fee_category_id).first()
    return category.title if category else "Fee Payment"


def build_receipt_no(transaction_id: int) -> str:
    return f"REC-{datetime.utcnow().year}-{transaction_id:04d}"

# --- MOUNT STATIC FILES ---
app.mount("/images", StaticFiles(directory="images"), name="images")
app.mount("/uploads", StaticFiles(directory="uploads"), name="uploads")

# --- CORS SETUP ---
# This is crucial. It allows your frontend (running on a different port or file URL)
# to make fetch() requests to this backend without getting blocked by the browser.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production, change this to your actual frontend domain
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- PYDANTIC SCHEMAS (Data Validation) ---
# These define exactly what JSON structure the frontend must send us.

class SelectedFee(BaseModel):
    category: str
    amount: float

class StudentRegistration(BaseModel):
    full_name: str
    roll_number: str
    branch: str
    password: str # We will hash this before saving!
    fees: List[SelectedFee]

# --- API ENDPOINTS ---

@app.post("/api/admin/register-student")
def register_student(student_data: StudentRegistration, db: Session = Depends(get_db)):
    
    # 1. Check if student already exists
    existing_user = db.query(models.User).filter(models.User.roll_number == student_data.roll_number).first()
    if existing_user:
        raise HTTPException(status_code=400, detail="Student with this Roll Number already exists.")

    # 2. Create the User Profile
    new_student = models.User(
        full_name=student_data.full_name,
        email=f"{student_data.roll_number.lower()}@bitsnarsampet.ac.in",
        password_hash=student_data.password, # Note: In production, use bcrypt to hash this!
        role=models.RoleType.STUDENT,
        roll_number=student_data.roll_number,
        branch=student_data.branch
    )
    db.add(new_student)
    db.commit()
    db.refresh(new_student) # Gets the new ID generated by the database

    # 3. Create the Fee Allocations for this student
    for fee in student_data.fees:
        # Check if the fee category exists in the DB, if not, create it dynamically
        category = db.query(models.FeeCategory).filter(models.FeeCategory.title == fee.category).first()
        if not category:
            category = models.FeeCategory(title=fee.category, default_amount=fee.amount, target_audience="ALL")
            db.add(category)
            db.commit()
            db.refresh(category)

        # Link the fee to the student in the StudentDue table
        new_due = models.StudentDue(
            student_id=new_student.id,
            fee_category_id=category.id,
            total_amount=fee.amount,
            paid_amount=0.0,
            status=models.StatusType.PENDING
        )
        db.add(new_due)
    
    db.commit()

    return {"message": "Student successfully registered and fees allocated.", "student_id": new_student.id}
@app.get("/api/admin/dashboard-stats")
def get_dashboard_stats(db: Session = Depends(get_db)):
    # 1. Count active students
    total_students = db.query(models.User).filter(models.User.role == models.RoleType.STUDENT).count()

    # 2. Calculate Total Paid and Total Due across the entire institute
    totals = db.query(
        func.sum(models.StudentDue.total_amount).label('total_allocated'),
        func.sum(models.StudentDue.paid_amount).label('total_paid')
    ).first()

    total_allocated = totals.total_allocated or 0
    total_paid = totals.total_paid or 0
    total_due = total_allocated - total_paid

    # 3. Fetch students who owe money for the Defaulters Table
    # This SQL query joins the User and StudentDue tables, groups them by student, and filters for due > 0
    defaulters_query = db.query(
        models.User.full_name,
        models.User.roll_number,
        models.User.branch,
        func.sum(models.StudentDue.total_amount - models.StudentDue.paid_amount).label('pending_amount')
    ).join(models.StudentDue).group_by(models.User.id).having(
        func.sum(models.StudentDue.total_amount - models.StudentDue.paid_amount) > 0
    ).all()

    # Format the data for the frontend
    defaulters_list = [
        {
            "id": row.roll_number,
            "name": row.full_name,
            "branch": row.branch,
            "due": row.pending_amount
        } for row in defaulters_query
    ]

    return {
        "active_enrollments": total_students,
        "total_paid": total_paid,
        "total_due": total_due,
        "total_allocated": total_allocated,
        "defaulters": defaulters_list
    }
# Add this new Pydantic schema near your other schemas at the top:
class LoginRequest(BaseModel):
    username: str
    password: str


class TriggerSingleAlertRequest(BaseModel):
    roll_number: str


class TriggerBulkAlertRequest(BaseModel):
    roll_numbers: List[str]


class VerificationActionRequest(BaseModel):
    action: str
    reason: str | None = None


class ProposeFeeRequest(BaseModel):
    title: str
    description: str
    amount: float
    target_audience: str  # "ALL" or specific branch like "CSE"


class SupportTicketRequest(BaseModel):
    student_id: int
    subject: str
    description: str
    category: str


class TicketResponseRequest(BaseModel):
    response: str
    status: str  # "IN_PROGRESS", "RESOLVED", "CLOSED"


# Add these endpoints at the bottom of main.py:

@app.post("/api/auth/login")
def login(credentials: LoginRequest, db: Session = Depends(get_db)):
    # 1. Admin Hardcoded Bypass (For demo purposes)
    if credentials.username == "admin@bitsnarsampet.ac.in" and credentials.password == "admin123":
        return {"message": "Login successful", "role": "ADMIN", "user_id": 0}
    
    # 2. Check Database for Student
    user = db.query(models.User).filter(models.User.roll_number == credentials.username).first()
    
    if not user or user.password_hash != credentials.password:
        raise HTTPException(status_code=401, detail="Invalid Roll Number or Password")
    
    return {
        "message": "Login successful", 
        "role": "STUDENT", 
        "user_id": user.id, 
        "name": user.full_name
    }


@app.post("/api/admin/trigger-alert")
def trigger_single_alert(payload: TriggerSingleAlertRequest, db: Session = Depends(get_db)):
    student = db.query(models.User).filter(models.User.roll_number == payload.roll_number).first()
    if not student:
        raise HTTPException(status_code=404, detail="Student not found")

    push_alert_for_student(
        student.id,
        "Admin Alert: Dues Pending",
        "Please clear your pending dues at the earliest to avoid late penalties.",
        notification_type="ALERT"
    )
    return {"message": "Alert sent successfully"}


@app.post("/api/admin/trigger-bulk-alert")
def trigger_bulk_alert(payload: TriggerBulkAlertRequest, db: Session = Depends(get_db)):
    if not payload.roll_numbers:
        raise HTTPException(status_code=400, detail="No students selected")

    students = db.query(models.User).filter(models.User.roll_number.in_(payload.roll_numbers)).all()
    if not students:
        raise HTTPException(status_code=404, detail="No matching students found")

    for student in students:
        push_alert_for_student(
            student.id,
            "Admin Alert: Dues Pending",
            "Please clear your pending dues at the earliest to avoid late penalties.",
            notification_type="ALERT"
        )

    return {"message": f"Bulk alerts dispatched to {len(students)} students"}


@app.get("/api/student/notifications/{student_id}")
def get_student_notifications(student_id: int):
    return {"notifications": ALERT_STORE.get(student_id, [])}


@app.post("/api/student/notifications/{student_id}/mark-read")
def mark_notifications_read(student_id: int):
    notifications = ALERT_STORE.get(student_id, [])
    for notification in notifications:
        notification["read"] = True
    ALERT_STORE[student_id] = notifications
    return {"message": "Notifications marked as read"}

@app.get("/api/student/dashboard/{student_id}")
def get_student_dashboard(student_id: int, db: Session = Depends(get_db)):
    # 1. Get the student profile
    student = db.query(models.User).filter(models.User.id == student_id).first()
    if not student:
        raise HTTPException(status_code=404, detail="Student not found")
    
    # 2. Get their specific fee allocations
    dues = db.query(models.StudentDue).filter(models.StudentDue.student_id == student_id).all()

    pending_transactions = db.query(models.Transaction).filter(
        models.Transaction.student_id == student_id,
        models.Transaction.status == models.TransactionStatus.PENDING_APPROVAL
    ).all()

    pending_by_category = {}
    for transaction in pending_transactions:
        key = transaction.fee_category_id
        pending_by_category[key] = pending_by_category.get(key, 0) + transaction.amount_paid
    
    # 3. Package the data for the frontend
    fees_data = []
    for due in dues:
        pending_amount = pending_by_category.get(due.fee_category_id, 0)
        fees_data.append({
            "category": due.fee_category.title,
            "description": due.fee_category.description,
            "total": due.total_amount,
            "paid": due.paid_amount,
            "pending": pending_amount,
            "is_proposed": bool(due.is_proposed)
        })

    recent_transactions = db.query(models.Transaction).filter(
        models.Transaction.student_id == student_id
    ).order_by(models.Transaction.submitted_at.desc()).limit(5).all()

    activity_data = []
    for transaction in recent_transactions:
        status_label = "Pending Approval"
        if transaction.status == models.TransactionStatus.VERIFIED:
            status_label = "Verified"
        elif transaction.status == models.TransactionStatus.REJECTED:
            status_label = "Rejected"

        activity_data.append({
            "category": get_fee_category_title(db, transaction.fee_category_id),
            "amount": transaction.amount_paid,
            "status": status_label,
            "utr": transaction.utr_number,
            "date": transaction.submitted_at.strftime("%d %b %Y") if transaction.submitted_at else ""
        })
        
    return {
        "student_name": student.full_name,
        "roll_number": student.roll_number,
        "branch": student.branch,
        "fees": fees_data,
        "recent_activity": activity_data
    }


@app.post("/api/student/submit-payment")
async def submit_payment_proof(
    student_id: int = Form(...),
    category: str = Form(...),
    amount: float = Form(...),
    utr_number: str = Form(...),
    proof_file: UploadFile = File(...),
    db: Session = Depends(get_db)
):
    student = db.query(models.User).filter(models.User.id == student_id).first()
    if not student:
        raise HTTPException(status_code=404, detail="Student not found")

    fee_category = db.query(models.FeeCategory).filter(models.FeeCategory.title == category).first()
    if not fee_category:
        raise HTTPException(status_code=404, detail="Fee category not found")

    due = db.query(models.StudentDue).filter(
        models.StudentDue.student_id == student_id,
        models.StudentDue.fee_category_id == fee_category.id
    ).first()

    if not due:
        raise HTTPException(status_code=404, detail="No due found for selected category")

    pending_sum = db.query(func.sum(models.Transaction.amount_paid)).filter(
        models.Transaction.student_id == student_id,
        models.Transaction.fee_category_id == fee_category.id,
        models.Transaction.status == models.TransactionStatus.PENDING_APPROVAL
    ).scalar() or 0

    remaining = due.total_amount - due.paid_amount - pending_sum
    if amount <= 0:
        raise HTTPException(status_code=400, detail="Amount should be greater than 0")
    if amount > remaining:
        raise HTTPException(status_code=400, detail=f"Amount exceeds remaining due ₹{remaining:.0f}")

    existing_utr = db.query(models.Transaction).filter(models.Transaction.utr_number == utr_number).first()
    if existing_utr:
        raise HTTPException(status_code=400, detail="UTR already submitted")

    file_ext = Path(proof_file.filename or "receipt.jpg").suffix or ".jpg"
    safe_name = f"{uuid.uuid4().hex}{file_ext}"
    saved_path = UPLOADS_DIR / safe_name

    content = await proof_file.read()
    with open(saved_path, "wb") as destination:
        destination.write(content)

    transaction = models.Transaction(
        student_id=student_id,
        fee_category_id=fee_category.id,
        amount_paid=amount,
        utr_number=utr_number,
        receipt_proof_url=f"/uploads/{safe_name}",
        status=models.TransactionStatus.PENDING_APPROVAL
    )
    db.add(transaction)
    db.commit()

    return {"message": "Payment proof submitted for admin verification"}


@app.get("/api/admin/verification-queue")
def get_verification_queue(db: Session = Depends(get_db)):
    transactions = db.query(models.Transaction).filter(
        models.Transaction.status == models.TransactionStatus.PENDING_APPROVAL
    ).order_by(models.Transaction.submitted_at.desc()).all()

    queue = []
    for transaction in transactions:
        student = transaction.student
        category = get_fee_category_title(db, transaction.fee_category_id)

        queue.append({
            "transaction_id": transaction.id,
            "date": transaction.submitted_at.strftime("%d %b %Y") if transaction.submitted_at else "",
            "student_name": student.full_name if student else "Unknown",
            "roll_number": student.roll_number if student else "",
            "branch": student.branch if student else "",
            "amount": transaction.amount_paid,
            "utr": transaction.utr_number,
            "category": category,
            "proof_url": transaction.receipt_proof_url
        })

    return {"queue": queue}


@app.post("/api/admin/verification-action/{transaction_id}")
def process_verification_action(transaction_id: int, payload: VerificationActionRequest, db: Session = Depends(get_db)):
    transaction = db.query(models.Transaction).filter(models.Transaction.id == transaction_id).first()
    if not transaction:
        raise HTTPException(status_code=404, detail="Transaction not found")

    if transaction.status != models.TransactionStatus.PENDING_APPROVAL:
        raise HTTPException(status_code=400, detail="Transaction already processed")

    action = payload.action.strip().lower()
    if action not in ["approve", "reject"]:
        raise HTTPException(status_code=400, detail="Invalid action")

    try:
        if action == "approve":
            due = db.query(models.StudentDue).filter(
                models.StudentDue.student_id == transaction.student_id,
                models.StudentDue.fee_category_id == transaction.fee_category_id
            ).first()

            if not due:
                raise HTTPException(status_code=404, detail="Student due not found")

            due.paid_amount = min(due.total_amount, due.paid_amount + transaction.amount_paid)
            due.status = models.StatusType.CLEARED if due.paid_amount >= due.total_amount else models.StatusType.PENDING
            transaction.status = models.TransactionStatus.VERIFIED

            category_title = get_fee_category_title(db, transaction.fee_category_id)
            receipt_no = build_receipt_no(transaction.id)

            # 1) Approval notification
            push_alert_for_student(
                transaction.student_id,
                "Payment Approved",
                f"Approved: ₹{transaction.amount_paid:,.0f} for {category_title} (UTR: {transaction.utr_number}).",
                notification_type="PAYMENT"
            )

            # 2) Receipt issued notification
            push_alert_for_student(
                transaction.student_id,
                "Receipt Issued",
                f"Receipt {receipt_no} is available in Document Center for ₹{transaction.amount_paid:,.0f} ({category_title}).",
                notification_type="PAYMENT"
            )
        else:
            reason = (payload.reason or "Payment proof did not meet verification requirements.").strip()
            if not reason:
                raise HTTPException(status_code=400, detail="Rejection reason is required")

            transaction.status = models.TransactionStatus.REJECTED
            REJECTION_REASON_STORE[transaction.id] = reason

            push_alert_for_student(
                transaction.student_id,
                "Payment Rejected",
                f"Your payment proof was rejected: {reason}. Amount will be refunded to your original payment account.",
                notification_type="PAYMENT"
            )

        db.commit()
        message = "Transaction approved successfully" if action == "approve" else "Transaction rejected successfully"
        return {"message": message}
    except SQLAlchemyError:
        db.rollback()
        raise HTTPException(status_code=500, detail="Failed to process verification")


@app.get("/api/student/receipts/{student_id}")
def get_student_receipts(student_id: int, db: Session = Depends(get_db)):
    receipts = db.query(models.Transaction).filter(
        models.Transaction.student_id == student_id,
        models.Transaction.status == models.TransactionStatus.VERIFIED
    ).order_by(models.Transaction.submitted_at.desc()).all()

    result = []
    for transaction in receipts:
        category = get_fee_category_title(db, transaction.fee_category_id)
        result.append({
            "transaction_id": transaction.id,
            "receipt_no": build_receipt_no(transaction.id),
            "amount": transaction.amount_paid,
            "category": category,
            "date": transaction.submitted_at.strftime("%d %b %Y") if transaction.submitted_at else ""
        })

    return {"receipts": result}


@app.get("/api/student/receipt/{transaction_id}/download")
def download_receipt(transaction_id: int, db: Session = Depends(get_db)):
    transaction = db.query(models.Transaction).filter(models.Transaction.id == transaction_id).first()
    if not transaction or transaction.status != models.TransactionStatus.VERIFIED:
        raise HTTPException(status_code=404, detail="Receipt not available")

    student = transaction.student
    category = get_fee_category_title(db, transaction.fee_category_id)
    receipt_no = build_receipt_no(transaction.id)
    issued_on = transaction.submitted_at.strftime("%d-%m-%Y") if transaction.submitted_at else datetime.utcnow().strftime("%d-%m-%Y")

    amount_display = f"₹{transaction.amount_paid:,.2f}"
    student_name = student.full_name if student else "N/A"
    roll_number = student.roll_number if student else "N/A"
    branch = student.branch if student else "N/A"

    receipt_html = f"""<!doctype html>
<html lang=\"en\">
<head>
    <meta charset=\"utf-8\" />
    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />
    <title>{receipt_no} - Official Receipt</title>
    <style>
        body {{ font-family: Arial, Helvetica, sans-serif; background: #fff; color: #111; margin: 0; padding: 24px; }}
        .page {{ max-width: 820px; margin: 0 auto; border: 1px solid #d1d5db; padding: 22px; }}
        .header {{ display: flex; gap: 16px; align-items: center; border-bottom: 1px solid #e5e7eb; padding-bottom: 14px; }}
        .logo {{ width: 64px; height: 64px; object-fit: contain; }}
        .title {{ line-height: 1.2; }}
        .title h1 {{ font-size: 18px; margin: 0; letter-spacing: 0.3px; }}
        .title p {{ margin: 4px 0 0; font-size: 12px; color: #374151; }}
        .meta {{ margin-top: 14px; display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }}
        .box {{ border: 1px solid #e5e7eb; padding: 12px; }}
        .box h2 {{ margin: 0 0 10px; font-size: 14px; }}
        .row {{ display: flex; justify-content: space-between; gap: 12px; font-size: 13px; padding: 6px 0; border-bottom: 1px dashed #e5e7eb; }}
        .row:last-child {{ border-bottom: 0; }}
        .label {{ color: #374151; }}
        .value {{ font-weight: 600; }}
        .footer {{ margin-top: 16px; display: grid; grid-template-columns: 1fr 1fr; gap: 12px; align-items: end; }}
        .stamp {{ height: 88px; border: 1px dashed #9ca3af; display: flex; align-items: center; justify-content: center; color: #6b7280; font-size: 12px; }}
        .sign {{ height: 88px; border: 1px dashed #9ca3af; display: flex; flex-direction: column; justify-content: flex-end; padding: 10px; }}
        .sign .line {{ border-top: 1px solid #111; margin-top: 18px; }}
        .sign .caption {{ font-size: 12px; color: #374151; margin-top: 6px; }}
        .note {{ margin-top: 14px; font-size: 12px; color: #374151; }}
        @media print {{ body {{ padding: 0; }} .page {{ border: 0; }} }}
    </style>
</head>
<body>
    <div class=\"page\">
        <div class=\"header\">
            <img class=\"logo\" src=\"/images/Bits-logo.png\" alt=\"BITS Logo\" />
            <div class=\"title\">
                <h1>BALAJI INSTITUTE OF TECHNOLOGY &amp; SCIENCE, NARSAMPET</h1>
                <p>Official Fee Payment Receipt</p>
            </div>
        </div>

        <div class=\"meta\">
            <div class=\"box\">
                <h2>Receipt Details</h2>
                <div class=\"row\"><span class=\"label\">Receipt No</span><span class=\"value\">{receipt_no}</span></div>
                <div class=\"row\"><span class=\"label\">Issued Date</span><span class=\"value\">{issued_on}</span></div>
                <div class=\"row\"><span class=\"label\">Status</span><span class=\"value\">VERIFIED</span></div>
            </div>
            <div class=\"box\">
                <h2>Student Details</h2>
                <div class=\"row\"><span class=\"label\">Name</span><span class=\"value\">{student_name}</span></div>
                <div class=\"row\"><span class=\"label\">Roll Number</span><span class=\"value\">{roll_number}</span></div>
                <div class=\"row\"><span class=\"label\">Branch</span><span class=\"value\">{branch}</span></div>
            </div>
        </div>

        <div class=\"box\" style=\"margin-top: 12px;\">
            <h2>Payment Details</h2>
            <div class=\"row\"><span class=\"label\">Fee Category</span><span class=\"value\">{category}</span></div>
            <div class=\"row\"><span class=\"label\">Amount Paid</span><span class=\"value\">{amount_display}</span></div>
            <div class=\"row\"><span class=\"label\">UTR Number</span><span class=\"value\">{transaction.utr_number}</span></div>
        </div>

        <div class=\"footer\">
            <div class=\"stamp\">Official Stamp</div>
            <div class=\"sign\">
                <div class=\"line\"></div>
                <div class=\"caption\">Authorized Signatory (Finance Office)</div>
            </div>
        </div>

        <div class=\"note\">This is a computer-generated receipt and does not require a physical signature. You may print this document for official use.</div>
    </div>
</body>
</html>""".strip()

    content = BytesIO(receipt_html.encode("utf-8"))
    filename = f"{receipt_no}.html"
    return StreamingResponse(
        content,
        media_type="text/html",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )

# --- STATIC FILES FOR FRONTEND ---
app.mount("/pages", StaticFiles(directory="pages"), name="pages")
app.mount("/scripts", StaticFiles(directory="scripts"), name="scripts")
app.mount("/styles", StaticFiles(directory="styles"), name="styles")
app.mount("/images", StaticFiles(directory="images"), name="images")
app.mount("/uploads", StaticFiles(directory="uploads"), name="uploads")

# --- FRONTEND ROUTES ---
@app.get("/")
async def serve_landing():
    return FileResponse('pages/landing.html')

@app.get("/api/admin/all-students")
def get_all_students(db: Session = Depends(get_db)):
    """Get all students with their dues information for the student management page"""
    students = db.query(models.User).filter(models.User.role == models.RoleType.STUDENT).all()
    
    result = []
    for student in students:
        # Calculate total due and paid for this student
        dues = db.query(models.StudentDue).filter(models.StudentDue.student_id == student.id).all()
        
        total_amount = sum(d.total_amount for d in dues)
        paid_amount = sum(d.paid_amount for d in dues)
        due_amount = total_amount - paid_amount
        
        result.append({
            "id": student.id,
            "full_name": student.full_name,
            "roll_number": student.roll_number,
            "branch": student.branch,
            "email": student.email,
            "total_due": due_amount,
            "paid_amount": paid_amount,
            "total_allocated": total_amount
        })
    
    return {"students": result}

@app.delete("/api/admin/delete-student/{student_id}")
async def delete_student(student_id: int, db: Session = Depends(get_db)):
    """Delete a student and all their associated records"""
    user = db.query(models.User).filter(models.User.id == student_id).first()
    
    if not user:
        raise HTTPException(status_code=404, detail="Student not found")

    try:
        inspector = inspect(db.bind)

        if inspector.has_table("student_dues"):
            db.query(models.StudentDue).filter(models.StudentDue.student_id == student_id).delete(synchronize_session=False)

        if inspector.has_table("transactions"):
            db.query(models.Transaction).filter(models.Transaction.student_id == student_id).delete(synchronize_session=False)

        db.delete(user)
        db.commit()
        return {"message": "Student deleted successfully"}
    except SQLAlchemyError:
        db.rollback()
        raise HTTPException(status_code=500, detail="Failed to delete student")


# ==========================================
# PROPOSE FEE ENDPOINTS
# ==========================================
@app.post("/api/admin/propose-fee")
def propose_new_fee(payload: ProposeFeeRequest, db: Session = Depends(get_db)):
    """Admin proposes a new fee and applies it to all matching students"""
    try:
        # 1. Create the fee category
        fee_category = models.FeeCategory(
            title=payload.title,
            description=payload.description,
            default_amount=payload.amount,
            target_audience=payload.target_audience
        )
        db.add(fee_category)
        db.flush()  # Get the ID

        # 2. Apply to all matching students
        if payload.target_audience.upper() == "ALL":
            students = db.query(models.User).filter(models.User.role == models.RoleType.STUDENT).all()
        else:
            students = db.query(models.User).filter(
                models.User.role == models.RoleType.STUDENT,
                models.User.branch == payload.target_audience
            ).all()

        # 3. Create student dues for each student with is_proposed flag
        for student in students:
            due = models.StudentDue(
                student_id=student.id,
                fee_category_id=fee_category.id,
                total_amount=payload.amount,
                paid_amount=0.0,
                status=models.StatusType.PENDING,
                is_proposed=1
            )
            db.add(due)

        db.commit()
        return {
            "message": f"Fee proposed successfully and applied to {len(students)} students",
            "students_count": len(students)
        }
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Failed to propose fee: {str(e)}")


@app.get("/api/admin/fee-proposals")
def get_fee_proposals(db: Session = Depends(get_db)):
    """Get all fee proposals history"""
    categories = db.query(models.FeeCategory).order_by(models.FeeCategory.created_at.desc()).all()
    
    proposals = []
    for category in categories:
        proposals.append({
            "id": category.id,
            "title": category.title,
            "description": category.description,
            "amount": category.default_amount,
            "target_audience": category.target_audience,
            "date": category.created_at.strftime("%d %b %Y") if category.created_at else ""
        })
    
    return {"proposals": proposals}


# ==========================================
# SUPPORT TICKET ENDPOINTS
# ==========================================
@app.post("/api/student/submit-ticket")
def submit_support_ticket(payload: SupportTicketRequest, db: Session = Depends(get_db)):
    """Student submits a support ticket"""
    try:
        # Generate ticket number
        ticket_count = db.query(models.SupportTicket).count()
        ticket_number = f"TKT-{datetime.utcnow().year}-{(ticket_count + 1):04d}"

        ticket = models.SupportTicket(
            student_id=payload.student_id,
            ticket_number=ticket_number,
            subject=payload.subject,
            description=payload.description,
            category=payload.category,
            status=models.TicketStatus.OPEN
        )
        db.add(ticket)
        db.commit()
        db.refresh(ticket)

        return {
            "message": "Support ticket submitted successfully",
            "ticket_number": ticket_number,
            "ticket_id": ticket.id
        }
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Failed to submit ticket: {str(e)}")


@app.get("/api/admin/support-tickets")
def get_all_support_tickets(db: Session = Depends(get_db)):
    """Admin gets all support tickets"""
    tickets = db.query(models.SupportTicket).order_by(models.SupportTicket.created_at.desc()).all()
    
    result = []
    for ticket in tickets:
        student = db.query(models.User).filter(models.User.id == ticket.student_id).first()
        result.append({
            "id": ticket.id,
            "ticket_number": ticket.ticket_number,
            "student_name": student.full_name if student else "Unknown",
            "student_roll": student.roll_number if student else "N/A",
            "subject": ticket.subject,
            "description": ticket.description,
            "category": ticket.category,
            "status": ticket.status.value,
            "created_at": ticket.created_at.strftime("%d %b %Y, %I:%M %p") if ticket.created_at else "",
            "admin_response": ticket.admin_response
        })
    
    return {"tickets": result}


@app.post("/api/admin/ticket/{ticket_id}/respond")
def respond_to_ticket(ticket_id: int, payload: TicketResponseRequest, db: Session = Depends(get_db)):
    """Admin responds to a support ticket"""
    ticket = db.query(models.SupportTicket).filter(models.SupportTicket.id == ticket_id).first()
    if not ticket:
        raise HTTPException(status_code=404, detail="Ticket not found")

    try:
        ticket.admin_response = payload.response
        ticket.status = models.TicketStatus[payload.status]
        
        if payload.status in ["RESOLVED", "CLOSED"]:
            ticket.resolved_at = datetime.utcnow()

        db.commit()
        return {"message": "Ticket updated successfully"}
    except Exception as e:
        db.rollback()
        raise HTTPException(status_code=500, detail=f"Failed to update ticket: {str(e)}")


@app.get("/api/student/my-tickets/{student_id}")
def get_student_tickets(student_id: int, db: Session = Depends(get_db)):
    """Student gets their own tickets"""
    tickets = db.query(models.SupportTicket).filter(
        models.SupportTicket.student_id == student_id
    ).order_by(models.SupportTicket.created_at.desc()).all()
    
    result = []
    for ticket in tickets:
        result.append({
            "id": ticket.id,
            "ticket_number": ticket.ticket_number,
            "subject": ticket.subject,
            "description": ticket.description,
            "category": ticket.category,
            "status": ticket.status.value,
            "created_at": ticket.created_at.strftime("%d %b %Y, %I:%M %p") if ticket.created_at else "",
            "admin_response": ticket.admin_response
        })
    
    return {"tickets": result}


# ==========================================
# EXCEL EXPORT ENDPOINT
# ==========================================
@app.get("/api/admin/export-dues")
def export_branch_dues(branch: str = "ALL", db: Session = Depends(get_db)):
    """Export branch-wise due report as Excel"""
    try:
        import io
        from openpyxl import Workbook
        from openpyxl.styles import Font, Alignment, PatternFill
        
        # Query students based on branch
        if branch.upper() == "ALL":
            students = db.query(models.User).filter(models.User.role == models.RoleType.STUDENT).all()
        else:
            students = db.query(models.User).filter(
                models.User.role == models.RoleType.STUDENT,
                models.User.branch == branch
            ).all()

        # Create workbook
        wb = Workbook()
        ws = wb.active
        ws.title = f"{branch} Dues Report"

        # Header styling
        header_fill = PatternFill(start_color="0F172A", end_color="0F172A", fill_type="solid")
        header_font = Font(bold=True, color="FFFFFF", size=12)
        header_alignment = Alignment(horizontal="center", vertical="center")

        # Headers
        headers = ["Roll Number", "Student Name", "Branch", "Total Allocated", "Total Paid", "Total Due"]
        ws.append(headers)
        
        for cell in ws[1]:
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = header_alignment

        # Data rows
        for student in students:
            dues = db.query(models.StudentDue).filter(models.StudentDue.student_id == student.id).all()
            
            total_allocated = sum(due.total_amount for due in dues)
            total_paid = sum(due.paid_amount for due in dues)
            total_due = total_allocated - total_paid

            ws.append([
                student.roll_number,
                student.full_name,
                student.branch,
                f"₹{total_allocated:,.2f}",
                f"₹{total_paid:,.2f}",
                f"₹{total_due:,.2f}"
            ])

        # Adjust column widths
        for column in ws.columns:
            max_length = 0
            column_letter = column[0].column_letter
            for cell in column:
                try:
                    if len(str(cell.value)) > max_length:
                        max_length = len(str(cell.value))
                except:
                    pass
            adjusted_width = min(max_length + 2, 50)
            ws.column_dimensions[column_letter].width = adjusted_width

        # Save to BytesIO
        output = io.BytesIO()
        wb.save(output)
        output.seek(0)

        filename = f"{branch}_Dues_Report_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.xlsx"
        
        return StreamingResponse(
            output,
            media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            headers={"Content-Disposition": f"attachment; filename={filename}"}
        )
    except ImportError:
        raise HTTPException(
            status_code=500, 
            detail="openpyxl library not installed. Run: pip install openpyxl"
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Export failed: {str(e)}")


@app.get("/login")
async def serve_login():
    return FileResponse('pages/login.html')

@app.get("/admin-dashboard")
async def serve_admin():
    return FileResponse('pages/admin.html')

@app.get("/student-dashboard")
async def serve_student():
    return FileResponse('pages/student.html')